version: '3.3'
services:
  app:
    image: briansworth/flask_api:ubuntu_xenial
    build:
      context: .
    environment:
      - FLASK_APP

  lb:
    image: briansworth/lb
    ports:
      - 80:80
    environment:
      - PROXY_UPSTREAM
    depends_on:
      - app
